# Generated by Django 4.0.3 on 2022-05-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank='True', null=True, upload_to='static/images/project'),
        ),
        migrations.AddField(
            model_name='project',
            name='visit_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
